{
 "title": "Claim Request Processing",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Claim Review Result", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Approved",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "claim_result_total{status=\"approved\"}"
    }
   ]
  },
  {
   "title": "Need Followup",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "claim_result_total{status=\"need-followup\"}"
    }
   ]
  },
  {
   "title": "Declined",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "claim_result_total{status=\"declined\"}"
    }
   ]
  },
  {
   "title": "Claim Review Result Overview",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(claim_result_total[$__interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Claim Review Result Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(claim_result_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Spring Boot - Actuator Statistics",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Average Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(spring_integration_send_seconds_sum{name=\"claimReqEventInput\"}[5m]) / rate(spring_integration_send_seconds_count{name=\"claimReqEventInput\"}[5m])",
     "legendFormat": "Processing Time"
    }
   ]
  },
  {
   "title": "Claim Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(spring_integration_send_seconds_count{name=\"claimReqEventInput\"}[5m])",
     "legendFormat": "Processing Rate"
    }
   ]
  },
  { "title": "Rabbitmq - Message Statistics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Message Rate - Published vs Consumed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_channel_messages_delivered_ack_total{queue=\"claimSubmitted.exchange.processor\"}[5m])",
     "legendFormat": "Claim processed"
    },
    {
     "expr": "sum by (queue) (rate(rabbitmq_queue_messages_published_total{queue=\"claimSubmitted.exchange.processor\"}[5m]))",
     "legendFormat": "New claim submitted"
    }
   ]
  },
  {
   "title": "Pending Claim Request Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"claimSubmitted.exchange.processor\"}",
     "legendFormat": "Published"
    }
   ]
  },
  {
   "title": "Message Published ",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (exchange) (increase(rabbitmq_channel_messages_published_total{exchange=\"claimSubmitted.exchange\"}[5m]))",
     "legendFormat": "Published"
    }
   ]
  },
  {
   "title": "Message Acknowledged",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (exchange) (increase(rabbitmq_channel_messages_acked_total{queue=\"claimSubmitted.exchange.processor\"}[5m]))",
     "legendFormat": "Acknowledged"
    }
   ]
  }
 ]
}